version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  deploy-staging:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - build
  build-deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: master
